appname="编译布局"
appver="1.3(alpha)"
appcode="1301"
packagename="com.jesse205.compilelayout"
mode="plugin"
debugmode=true
user_permission={
  "WRITE_EXTERNAL_STORAGE",
  "MANAGE_EXTERNAL_STORAGE",
  "READ_EXTERNAL_STORAGE"
}